import React from 'react'


export const countryCodes = [ 
  { "value": "+93", "label": "+93 AF" },
  { "value": "+358", "label": "+358 AX" },
  { "value": "+355", "label": "+355 AL" },
  { "value": "+213", "label": "+213 DZ" },
  { "value": "+1684", "label": "+1684 AS" },
  { "value": "+376", "label": "+376 AD" },
  { "value": "+244", "label": "+244 AO" },
  { "value": "+1264", "label": "+1264 AI" },
  { "value": "+672", "label": "+672 AQ" },
  { "value": "+1268", "label": "+1268 AG" },
  { "value": "+54", "label": "+54 AR" },
  { "value": "+374", "label": "+374 AM" },
  { "value": "+297", "label": "+297 AW" },
  { "value": "+61", "label": "+61 AU" },
  { "value": "+43", "label": "+43 AT" },
  { "value": "+994", "label": "+994 AZ" },
  { "value": "+1242", "label": "+1242 BS" },
  { "value": "+973", "label": "+973 BH" },
  { "value": "+880", "label": "+880 BD" },
  { "value": "+1246", "label": "+1246 BB" },
  { "value": "+375", "label": "+375 BY" },
  { "value": "+32", "label": "+32 BE" },
  { "value": "+501", "label": "+501 BZ" },
  { "value": "+229", "label": "+229 BJ" },
  { "value": "+1441", "label": "+1441 BM" },
  { "value": "+975", "label": "+975 BT" },
  { "value": "+591", "label": "+591 BO" },
  { "value": "+387", "label": "+387 BA" },
  { "value": "+267", "label": "+267 BW" },
  { "value": "+47", "label": "+47 BV" },
  { "value": "+55", "label": "+55 BR" },
  { "value": "+246", "label": "+246 IO" },
  { "value": "+673", "label": "+673 BN" },
  { "value": "+359", "label": "+359 BG" },
  { "value": "+226", "label": "+226 BF" },
  { "value": "+257", "label": "+257 BI" },
  { "value": "+855", "label": "+855 KH" },
  { "value": "+237", "label": "+237 CM" },
  { "value": "+1", "label": "+1 CA" },
  { "value": "+238", "label": "+238 CV" },
  { "value": "+ 345", "label": "+ 345 KY" },
  { "value": "+236", "label": "+236 CF" },
  { "value": "+235", "label": "+235 TD" },
  { "value": "+56", "label": "+56 CL" },
  { "value": "+86", "label": "+86 CN" },
  { "value": "+61", "label": "+61 CX" },
  { "value": "+61", "label": "+61 CC" },
  { "value": "+57", "label": "+57 CO" },
  { "value": "+269", "label": "+269 KM" },
  { "value": "+242", "label": "+242 CG" },
  { "value": "+243", "label": "+243 CD" },
  { "value": "+682", "label": "+682 CK" },
  { "value": "+506", "label": "+506 CR" },
  { "value": "+225", "label": "+225 CI" },
  { "value": "+385", "label": "+385 HR" },
  { "value": "+53", "label": "+53 CU" },
  { "value": "+357", "label": "+357 CY" },
  { "value": "+420", "label": "+420 CZ" },
  { "value": "+45", "label": "+45 DK" },
  { "value": "+253", "label": "+253 DJ" },
  { "value": "+1767", "label": "+1767 DM" },
  { "value": "+1849", "label": "+1849 DO" },
  { "value": "+593", "label": "+593 EC" },
  { "value": "+20", "label": "+20 EG" },
  { "value": "+503", "label": "+503 SV" },
  { "value": "+240", "label": "+240 GQ" },
  { "value": "+291", "label": "+291 ER" },
  { "value": "+372", "label": "+372 EE" },
  { "value": "+251", "label": "+251 ET" },
  { "value": "+500", "label": "+500 FK" },
  { "value": "+298", "label": "+298 FO" },
  { "value": "+679", "label": "+679 FJ" },
  { "value": "+358", "label": "+358 FI" },
  { "value": "+33", "label": "+33 FR" },
  { "value": "+594", "label": "+594 GF" },
  { "value": "+689", "label": "+689 PF" },
  { "value": "+262", "label": "+262 TF" },
  { "value": "+241", "label": "+241 GA" },
  { "value": "+220", "label": "+220 GM" },
  { "value": "+995", "label": "+995 GE" },
  { "value": "+49", "label": "+49 DE" },
  { "value": "+233", "label": "+233 GH" },
  { "value": "+350", "label": "+350 GI" },
  { "value": "+30", "label": "+30 GR" },
  { "value": "+299", "label": "+299 GL" },
  { "value": "+1473", "label": "+1473 GD" },
  { "value": "+590", "label": "+590 GP" },
  { "value": "+1671", "label": "+1671 GU" },
  { "value": "+502", "label": "+502 GT" },
  { "value": "+44", "label": "+44 GG" },
  { "value": "+224", "label": "+224 GN" },
  { "value": "+245", "label": "+245 GW" },
  { "value": "+592", "label": "+592 GY" },
  { "value": "+509", "label": "+509 HT" },
  { "value": "+0", "label": "+0 HM" },
  { "value": "+379", "label": "+379 VA" },
  { "value": "+504", "label": "+504 HN" },
  { "value": "+852", "label": "+852 HK" },
  { "value": "+36", "label": "+36 HU" },
  { "value": "+354", "label": "+354 IS" },
  { "value": "+91", "label": "+91 IN" },
  { "value": "+62", "label": "+62 ID" },
  { "value": "+98", "label": "+98 IR" },
  { "value": "+964", "label": "+964 IQ" },
  { "value": "+353", "label": "+353 IE" },
  { "value": "+44", "label": "+44 IM" },
  { "value": "+972", "label": "+972 IL" },
  { "value": "+39", "label": "+39 IT" },
  { "value": "+1876", "label": "+1876 JM" },
  { "value": "+81", "label": "+81 JP" },
  { "value": "+44", "label": "+44 JE" },
  { "value": "+962", "label": "+962 JO" },
  { "value": "+7", "label": "+7 KZ" },
  { "value": "+254", "label": "+254 KE" },
  { "value": "+686", "label": "+686 KI" },
  { "value": "+850", "label": "+850 KP" },
  { "value": "+82", "label": "+82 KR" },
  { "value": "+383", "label": "+383 XK" },
  { "value": "+965", "label": "+965 KW" },
  { "value": "+996", "label": "+996 KG" },
  { "value": "+856", "label": "+856 LA" },
  { "value": "+371", "label": "+371 LV" },
  { "value": "+961", "label": "+961 LB" },
  { "value": "+266", "label": "+266 LS" },
  { "value": "+231", "label": "+231 LR" },
  { "value": "+218", "label": "+218 LY" },
  { "value": "+423", "label": "+423 LI" },
  { "value": "+370", "label": "+370 LT" },
  { "value": "+352", "label": "+352 LU" },
  { "value": "+853", "label": "+853 MO" },
  { "value": "+389", "label": "+389 MK" },
  { "value": "+261", "label": "+261 MG" },
  { "value": "+265", "label": "+265 MW" },
  { "value": "+60", "label": "+60 MY" },
  { "value": "+960", "label": "+960 MV" },
  { "value": "+223", "label": "+223 ML" },
  { "value": "+356", "label": "+356 MT" },
  { "value": "+692", "label": "+692 MH" },
  { "value": "+596", "label": "+596 MQ" },
  { "value": "+222", "label": "+222 MR" },
  { "value": "+230", "label": "+230 MU" },
  { "value": "+262", "label": "+262 YT" },
  { "value": "+52", "label": "+52 MX" },
  { "value": "+691", "label": "+691 FM" },
  { "value": "+373", "label": "+373 MD" },
  { "value": "+377", "label": "+377 MC" },
  { "value": "+976", "label": "+976 MN" },
  { "value": "+382", "label": "+382 ME" },
  { "value": "+1664", "label": "+1664 MS" },
  { "value": "+212", "label": "+212 MA" },
  { "value": "+258", "label": "+258 MZ" },
  { "value": "+95", "label": "+95 MM" },
  { "value": "+264", "label": "+264 NA" },
  { "value": "+674", "label": "+674 NR" },
  { "value": "+977", "label": "+977 NP" },
  { "value": "+31", "label": "+31 NL" },
  { "value": "+599", "label": "+599 AN" },
  { "value": "+687", "label": "+687 NC" },
  { "value": "+64", "label": "+64 NZ" },
  { "value": "+505", "label": "+505 NI" },
  { "value": "+227", "label": "+227 NE" },
  { "value": "+234", "label": "+234 NG" },
  { "value": "+683", "label": "+683 NU" },
  { "value": "+672", "label": "+672 NF" },
  { "value": "+1670", "label": "+1670 MP" },
  { "value": "+47", "label": "+47 NO" },
  { "value": "+968", "label": "+968 OM" },
  { "value": "+92", "label": "+92 PK" },
  { "value": "+680", "label": "+680 PW" },
  { "value": "+970", "label": "+970 PS" },
  { "value": "+507", "label": "+507 PA" },
  { "value": "+675", "label": "+675 PG" },
  { "value": "+595", "label": "+595 PY" },
  { "value": "+51", "label": "+51 PE" },
  { "value": "+63", "label": "+63 PH" },
  { "value": "+64", "label": "+64 PN" },
  { "value": "+48", "label": "+48 PL" },
  { "value": "+351", "label": "+351 PT" },
  { "value": "+1939", "label": "+1939 PR" },
  { "value": "+974", "label": "+974 QA" },
  { "value": "+40", "label": "+40 RO" },
  { "value": "+7", "label": "+7 RU" },
  { "value": "+250", "label": "+250 RW" },
  { "value": "+262", "label": "+262 RE" },
  { "value": "+590", "label": "+590 BL" },
  { "value": "+290", "label": "+290 SH" },
  { "value": "+1869", "label": "+1869 KN" },
  { "value": "+1758", "label": "+1758 LC" },
  { "value": "+590", "label": "+590 MF" },
  { "value": "+508", "label": "+508 PM" },
  { "value": "+1784", "label": "+1784 VC" },
  { "value": "+685", "label": "+685 WS" },
  { "value": "+378", "label": "+378 SM" },
  { "value": "+239", "label": "+239 ST" },
  { "value": "+966", "label": "+966 SA" },
  { "value": "+221", "label": "+221 SN" },
  { "value": "+381", "label": "+381 RS" },
  { "value": "+248", "label": "+248 SC" },
  { "value": "+232", "label": "+232 SL" },
  { "value": "+65", "label": "+65 SG" },
  { "value": "+421", "label": "+421 SK" },
  { "value": "+386", "label": "+386 SI" },
  { "value": "+677", "label": "+677 SB" },
  { "value": "+252", "label": "+252 SO" },
  { "value": "+27", "label": "+27 ZA" },
  { "value": "+211", "label": "+211 SS" },
  { "value": "+500", "label": "+500 GS" },
  { "value": "+34", "label": "+34 ES" },
  { "value": "+94", "label": "+94 LK" },
  { "value": "+249", "label": "+249 SD" },
  { "value": "+597", "label": "+597 SR" },
  { "value": "+47", "label": "+47 SJ" },
  { "value": "+268", "label": "+268 SZ" },
  { "value": "+46", "label": "+46 SE" },
  { "value": "+41", "label": "+41 CH" },
  { "value": "+963", "label": "+963 SY" },
  { "value": "+886", "label": "+886 TW" },
  { "value": "+992", "label": "+992 TJ" },
  { "value": "+255", "label": "+255 TZ" },
  { "value": "+66", "label": "+66 TH" },
  { "value": "+670", "label": "+670 TL" },
  { "value": "+228", "label": "+228 TG" },
  { "value": "+690", "label": "+690 TK" },
  { "value": "+676", "label": "+676 TO" },
  { "value": "+1868", "label": "+1868 TT" },
  { "value": "+216", "label": "+216 TN" },
  { "value": "+90", "label": "+90 TR" },
  { "value": "+993", "label": "+993 TM" },
  { "value": "+1649", "label": "+1649 TC" },
  { "value": "+688", "label": "+688 TV" },
  { "value": "+256", "label": "+256 UG" },
  { "value": "+380", "label": "+380 UA" },
  { "value": "+971", "label": "+971 AE" },
  { "value": "+44", "label": "+44 GB" },
  { "value": "+1", "label": "+1 US" },
  { "value": "+598", "label": "+598 UY" },
  { "value": "+998", "label": "+998 UZ" },
  { "value": "+678", "label": "+678 VU" },
  { "value": "+58", "label": "+58 VE" },
  { "value": "+84", "label": "+84 VN" },
  { "value": "+1284", "label": "+1284 VG" },
  { "value": "+1340", "label": "+1340 VI" },
  { "value": "+681", "label": "+681 WF" },
  { "value": "+967", "label": "+967 YE" },
  { "value": "+260", "label": "+260 ZM" },
  { "value": "+263", "label": "+263 ZW" } 
];

const dailCodes = [ 
  { "name": "Afghanistan", "dial_code": "+93", "code": "AF" },
  { "name": "Åland Islands", "dial_code": "+358", "code": "AX" },
  { "name": "Albania", "dial_code": "+355", "code": "AL" },
  { "name": "Algeria", "dial_code": "+213", "code": "DZ" },
  { "name": "American Samoa", "dial_code": "+1684", "code": "AS" },
  { "name": "Andorra", "dial_code": "+376", "code": "AD" },
  { "name": "Angola", "dial_code": "+244", "code": "AO" },
  { "name": "Anguilla", "dial_code": "+1264", "code": "AI" },
  { "name": "Antarctica", "dial_code": "+672", "code": "AQ" },
  { "name": "Antigua and Barbuda", "dial_code": "+1268", "code": "AG" },
  { "name": "Argentina", "dial_code": "+54", "code": "AR" },
  { "name": "Armenia", "dial_code": "+374", "code": "AM" },
  { "name": "Aruba", "dial_code": "+297", "code": "AW" },
  { "name": "Australia", "dial_code": "+61", "code": "AU" },
  { "name": "Austria", "dial_code": "+43", "code": "AT" },
  { "name": "Azerbaijan", "dial_code": "+994", "code": "AZ" },
  { "name": "Bahamas", "dial_code": "+1242", "code": "BS" },
  { "name": "Bahrain", "dial_code": "+973", "code": "BH" },
  { "name": "Bangladesh", "dial_code": "+880", "code": "BD" },
  { "name": "Barbados", "dial_code": "+1246", "code": "BB" },
  { "name": "Belarus", "dial_code": "+375", "code": "BY" },
  { "name": "Belgium", "dial_code": "+32", "code": "BE" },
  { "name": "Belize", "dial_code": "+501", "code": "BZ" },
  { "name": "Benin", "dial_code": "+229", "code": "BJ" },
  { "name": "Bermuda", "dial_code": "+1441", "code": "BM" },
  { "name": "Bhutan", "dial_code": "+975", "code": "BT" },
  { "name": "Bolivia, Plurinational State of bolivia", "dial_code": "+591", "code": "BO" },
  { "name": "Bosnia and Herzegovina", "dial_code": "+387", "code": "BA" },
  { "name": "Botswana", "dial_code": "+267", "code": "BW" },
  { "name": "Bouvet Island", "dial_code": "+47", "code": "BV" },
  { "name": "Brazil", "dial_code": "+55", "code": "BR" },
  { "name": "British Indian Ocean Territory", "dial_code": "+246", "code": "IO" },
  { "name": "Brunei Darussalam", "dial_code": "+673", "code": "BN" },
  { "name": "Bulgaria", "dial_code": "+359", "code": "BG" },
  { "name": "Burkina Faso", "dial_code": "+226", "code": "BF" },
  { "name": "Burundi", "dial_code": "+257", "code": "BI" },
  { "name": "Cambodia", "dial_code": "+855", "code": "KH" },
  { "name": "Cameroon", "dial_code": "+237", "code": "CM" },
  { "name": "Canada", "dial_code": "+1", "code": "CA" },
  { "name": "Cape Verde", "dial_code": "+238", "code": "CV" },
  { "name": "Cayman Islands", "dial_code": "+ 345", "code": "KY" },
  { "name": "Central African Republic", "dial_code": "+236", "code": "CF" },
  { "name": "Chad", "dial_code": "+235", "code": "TD" },
  { "name": "Chile", "dial_code": "+56", "code": "CL" },
  { "name": "China", "dial_code": "+86", "code": "CN" },
  { "name": "Christmas Island", "dial_code": "+61", "code": "CX" },
  { "name": "Cocos (Keeling) Islands", "dial_code": "+61", "code": "CC" },
  { "name": "Colombia", "dial_code": "+57", "code": "CO" },
  { "name": "Comoros", "dial_code": "+269", "code": "KM" },
  { "name": "Congo", "dial_code": "+242", "code": "CG" },
  { "name": "Congo, The Democratic Republic of the Congo", "dial_code": "+243", "code": "CD" },
  { "name": "Cook Islands", "dial_code": "+682", "code": "CK" },
  { "name": "Costa Rica", "dial_code": "+506", "code": "CR" },
  { "name": "Cote d'Ivoire", "dial_code": "+225", "code": "CI" },
  { "name": "Croatia", "dial_code": "+385", "code": "HR" },
  { "name": "Cuba", "dial_code": "+53", "code": "CU" },
  { "name": "Cyprus", "dial_code": "+357", "code": "CY" },
  { "name": "Czech Republic", "dial_code": "+420", "code": "CZ" },
  { "name": "Denmark", "dial_code": "+45", "code": "DK" },
  { "name": "Djibouti", "dial_code": "+253", "code": "DJ" },
  { "name": "Dominica", "dial_code": "+1767", "code": "DM" },
  { "name": "Dominican Republic", "dial_code": "+1849", "code": "DO" },
  { "name": "Ecuador", "dial_code": "+593", "code": "EC" },
  { "name": "Egypt", "dial_code": "+20", "code": "EG" },
  { "name": "El Salvador", "dial_code": "+503", "code": "SV" },
  { "name": "Equatorial Guinea", "dial_code": "+240", "code": "GQ" },
  { "name": "Eritrea", "dial_code": "+291", "code": "ER" },
  { "name": "Estonia", "dial_code": "+372", "code": "EE" },
  { "name": "Ethiopia", "dial_code": "+251", "code": "ET" },
  { "name": "Falkland Islands (Malvinas)", "dial_code": "+500", "code": "FK" },
  { "name": "Faroe Islands", "dial_code": "+298", "code": "FO" },
  { "name": "Fiji", "dial_code": "+679", "code": "FJ" },
  { "name": "Finland", "dial_code": "+358", "code": "FI" },
  { "name": "France", "dial_code": "+33", "code": "FR" },
  { "name": "French Guiana", "dial_code": "+594", "code": "GF" },
  { "name": "French Polynesia", "dial_code": "+689", "code": "PF" },
  { "name": "French Southern Territories", "dial_code": "+262", "code": "TF" },
  { "name": "Gabon", "dial_code": "+241", "code": "GA" },
  { "name": "Gambia", "dial_code": "+220", "code": "GM" },
  { "name": "Georgia", "dial_code": "+995", "code": "GE" },
  { "name": "Germany", "dial_code": "+49", "code": "DE" },
  { "name": "Ghana", "dial_code": "+233", "code": "GH" },
  { "name": "Gibraltar", "dial_code": "+350", "code": "GI" },
  { "name": "Greece", "dial_code": "+30", "code": "GR" },
  { "name": "Greenland", "dial_code": "+299", "code": "GL" },
  { "name": "Grenada", "dial_code": "+1473", "code": "GD" },
  { "name": "Guadeloupe", "dial_code": "+590", "code": "GP" },
  { "name": "Guam", "dial_code": "+1671", "code": "GU" },
  { "name": "Guatemala", "dial_code": "+502", "code": "GT" },
  { "name": "Guernsey", "dial_code": "+44", "code": "GG" },
  { "name": "Guinea", "dial_code": "+224", "code": "GN" },
  { "name": "Guinea-Bissau", "dial_code": "+245", "code": "GW" },
  { "name": "Guyana", "dial_code": "+592", "code": "GY" },
  { "name": "Haiti", "dial_code": "+509", "code": "HT" },
  { "name": "Heard Island and Mcdonald Islands", "dial_code": "+0", "code": "HM" },
  { "name": "Holy See (Vatican City State)", "dial_code": "+379", "code": "VA" },
  { "name": "Honduras", "dial_code": "+504", "code": "HN" },
  { "name": "Hong Kong", "dial_code": "+852", "code": "HK" },
  { "name": "Hungary", "dial_code": "+36", "code": "HU" },
  { "name": "Iceland", "dial_code": "+354", "code": "IS" },
  { "name": "India", "dial_code": "+91", "code": "IN" },
  { "name": "Indonesia", "dial_code": "+62", "code": "ID" },
  { "name": "Iran, Islamic Republic of Persian Gulf", "dial_code": "+98", "code": "IR" },
  { "name": "Iraq", "dial_code": "+964", "code": "IQ" },
  { "name": "Ireland", "dial_code": "+353", "code": "IE" },
  { "name": "Isle of Man", "dial_code": "+44", "code": "IM" },
  { "name": "Israel", "dial_code": "+972", "code": "IL" },
  { "name": "Italy", "dial_code": "+39", "code": "IT" },
  { "name": "Jamaica", "dial_code": "+1876", "code": "JM" },
  { "name": "Japan", "dial_code": "+81", "code": "JP" },
  { "name": "Jersey", "dial_code": "+44", "code": "JE" },
  { "name": "Jordan", "dial_code": "+962", "code": "JO" },
  { "name": "Kazakhstan", "dial_code": "+7", "code": "KZ" },
  { "name": "Kenya", "dial_code": "+254", "code": "KE" },
  { "name": "Kiribati", "dial_code": "+686", "code": "KI" },
  { "name": "Korea, Democratic People's Republic of Korea", "dial_code": "+850", "code": "KP" },
  { "name": "Korea, Republic of South Korea", "dial_code": "+82", "code": "KR" },
  { "name": "Kosovo", "dial_code": "+383", "code": "XK" },
  { "name": "Kuwait", "dial_code": "+965", "code": "KW" },
  { "name": "Kyrgyzstan", "dial_code": "+996", "code": "KG" },
  { "name": "Laos", "dial_code": "+856", "code": "LA" },
  { "name": "Latvia", "dial_code": "+371", "code": "LV" },
  { "name": "Lebanon", "dial_code": "+961", "code": "LB" },
  { "name": "Lesotho", "dial_code": "+266", "code": "LS" },
  { "name": "Liberia", "dial_code": "+231", "code": "LR" },
  { "name": "Libyan Arab Jamahiriya", "dial_code": "+218", "code": "LY" },
  { "name": "Liechtenstein", "dial_code": "+423", "code": "LI" },
  { "name": "Lithuania", "dial_code": "+370", "code": "LT" },
  { "name": "Luxembourg", "dial_code": "+352", "code": "LU" },
  { "name": "Macao", "dial_code": "+853", "code": "MO" },
  { "name": "Macedonia", "dial_code": "+389", "code": "MK" },
  { "name": "Madagascar", "dial_code": "+261", "code": "MG" },
  { "name": "Malawi", "dial_code": "+265", "code": "MW" },
  { "name": "Malaysia", "dial_code": "+60", "code": "MY" },
  { "name": "Maldives", "dial_code": "+960", "code": "MV" },
  { "name": "Mali", "dial_code": "+223", "code": "ML" },
  { "name": "Malta", "dial_code": "+356", "code": "MT" },
  { "name": "Marshall Islands", "dial_code": "+692", "code": "MH" },
  { "name": "Martinique", "dial_code": "+596", "code": "MQ" },
  { "name": "Mauritania", "dial_code": "+222", "code": "MR" },
  { "name": "Mauritius", "dial_code": "+230", "code": "MU" },
  { "name": "Mayotte", "dial_code": "+262", "code": "YT" },
  { "name": "Mexico", "dial_code": "+52", "code": "MX" },
  { "name": "Micronesia, Federated States of Micronesia", "dial_code": "+691", "code": "FM" },
  { "name": "Moldova", "dial_code": "+373", "code": "MD" },
  { "name": "Monaco", "dial_code": "+377", "code": "MC" },
  { "name": "Mongolia", "dial_code": "+976", "code": "MN" },
  { "name": "Montenegro", "dial_code": "+382", "code": "ME" },
  { "name": "Montserrat", "dial_code": "+1664", "code": "MS" },
  { "name": "Morocco", "dial_code": "+212", "code": "MA" },
  { "name": "Mozambique", "dial_code": "+258", "code": "MZ" },
  { "name": "Myanmar", "dial_code": "+95", "code": "MM" },
  { "name": "Namibia", "dial_code": "+264", "code": "NA" },
  { "name": "Nauru", "dial_code": "+674", "code": "NR" },
  { "name": "Nepal", "dial_code": "+977", "code": "NP" },
  { "name": "Netherlands", "dial_code": "+31", "code": "NL" },
  { "name": "Netherlands Antilles", "dial_code": "+599", "code": "AN" },
  { "name": "New Caledonia", "dial_code": "+687", "code": "NC" },
  { "name": "New Zealand", "dial_code": "+64", "code": "NZ" },
  { "name": "Nicaragua", "dial_code": "+505", "code": "NI" },
  { "name": "Niger", "dial_code": "+227", "code": "NE" },
  { "name": "Nigeria", "dial_code": "+234", "code": "NG" },
  { "name": "Niue", "dial_code": "+683", "code": "NU" },
  { "name": "Norfolk Island", "dial_code": "+672", "code": "NF" },
  { "name": "Northern Mariana Islands", "dial_code": "+1670", "code": "MP" },
  { "name": "Norway", "dial_code": "+47", "code": "NO" },
  { "name": "Oman", "dial_code": "+968", "code": "OM" },
  { "name": "Pakistan", "dial_code": "+92", "code": "PK" },
  { "name": "Palau", "dial_code": "+680", "code": "PW" },
  { "name": "Palestinian Territory, Occupied", "dial_code": "+970", "code": "PS" },
  { "name": "Panama", "dial_code": "+507", "code": "PA" },
  { "name": "Papua New Guinea", "dial_code": "+675", "code": "PG" },
  { "name": "Paraguay", "dial_code": "+595", "code": "PY" },
  { "name": "Peru", "dial_code": "+51", "code": "PE" },
  { "name": "Philippines", "dial_code": "+63", "code": "PH" },
  { "name": "Pitcairn", "dial_code": "+64", "code": "PN" },
  { "name": "Poland", "dial_code": "+48", "code": "PL" },
  { "name": "Portugal", "dial_code": "+351", "code": "PT" },
  { "name": "Puerto Rico", "dial_code": "+1939", "code": "PR" },
  { "name": "Qatar", "dial_code": "+974", "code": "QA" },
  { "name": "Romania", "dial_code": "+40", "code": "RO" },
  { "name": "Russia", "dial_code": "+7", "code": "RU" },
  { "name": "Rwanda", "dial_code": "+250", "code": "RW" },
  { "name": "Reunion", "dial_code": "+262", "code": "RE" },
  { "name": "Saint Barthelemy", "dial_code": "+590", "code": "BL" },
  { "name": "Saint Helena, Ascension and Tristan Da Cunha", "dial_code": "+290", "code": "SH" },
  { "name": "Saint Kitts and Nevis", "dial_code": "+1869", "code": "KN" },
  { "name": "Saint Lucia", "dial_code": "+1758", "code": "LC" },
  { "name": "Saint Martin", "dial_code": "+590", "code": "MF" },
  { "name": "Saint Pierre and Miquelon", "dial_code": "+508", "code": "PM" },
  { "name": "Saint Vincent and the Grenadines", "dial_code": "+1784", "code": "VC" },
  { "name": "Samoa", "dial_code": "+685", "code": "WS" },
  { "name": "San Marino", "dial_code": "+378", "code": "SM" },
  { "name": "Sao Tome and Principe", "dial_code": "+239", "code": "ST" },
  { "name": "Saudi Arabia", "dial_code": "+966", "code": "SA" },
  { "name": "Senegal", "dial_code": "+221", "code": "SN" },
  { "name": "Serbia", "dial_code": "+381", "code": "RS" },
  { "name": "Seychelles", "dial_code": "+248", "code": "SC" },
  { "name": "Sierra Leone", "dial_code": "+232", "code": "SL" },
  { "name": "Singapore", "dial_code": "+65", "code": "SG" },
  { "name": "Slovakia", "dial_code": "+421", "code": "SK" },
  { "name": "Slovenia", "dial_code": "+386", "code": "SI" },
  { "name": "Solomon Islands", "dial_code": "+677", "code": "SB" },
  { "name": "Somalia", "dial_code": "+252", "code": "SO" },
  { "name": "South Africa", "dial_code": "+27", "code": "ZA" },
  { "name": "South Sudan", "dial_code": "+211", "code": "SS" },
  { "name": "South Georgia and the South Sandwich Islands", "dial_code": "+500", "code": "GS" },
  { "name": "Spain", "dial_code": "+34", "code": "ES" },
  { "name": "Sri Lanka", "dial_code": "+94", "code": "LK" },
  { "name": "Sudan", "dial_code": "+249", "code": "SD" },
  { "name": "Suriname", "dial_code": "+597", "code": "SR" },
  { "name": "Svalbard and Jan Mayen", "dial_code": "+47", "code": "SJ" },
  { "name": "Swaziland", "dial_code": "+268", "code": "SZ" },
  { "name": "Sweden", "dial_code": "+46", "code": "SE" },
  { "name": "Switzerland", "dial_code": "+41", "code": "CH" },
  { "name": "Syrian Arab Republic", "dial_code": "+963", "code": "SY" },
  { "name": "Taiwan", "dial_code": "+886", "code": "TW" },
  { "name": "Tajikistan", "dial_code": "+992", "code": "TJ" },
  { "name": "Tanzania, United Republic of Tanzania", "dial_code": "+255", "code": "TZ" },
  { "name": "Thailand", "dial_code": "+66", "code": "TH" },
  { "name": "Timor-Leste", "dial_code": "+670", "code": "TL" },
  { "name": "Togo", "dial_code": "+228", "code": "TG" },
  { "name": "Tokelau", "dial_code": "+690", "code": "TK" },
  { "name": "Tonga", "dial_code": "+676", "code": "TO" },
  { "name": "Trinidad and Tobago", "dial_code": "+1868", "code": "TT" },
  { "name": "Tunisia", "dial_code": "+216", "code": "TN" },
  { "name": "Turkey", "dial_code": "+90", "code": "TR" },
  { "name": "Turkmenistan", "dial_code": "+993", "code": "TM" },
  { "name": "Turks and Caicos Islands", "dial_code": "+1649", "code": "TC" },
  { "name": "Tuvalu", "dial_code": "+688", "code": "TV" },
  { "name": "Uganda", "dial_code": "+256", "code": "UG" },
  { "name": "Ukraine", "dial_code": "+380", "code": "UA" },
  { "name": "United Arab Emirates", "dial_code": "+971", "code": "AE" },
  { "name": "United Kingdom", "dial_code": "+44", "code": "GB" },
  { "name": "United States", "dial_code": "+1", "code": "US" },
  { "name": "Uruguay", "dial_code": "+598", "code": "UY" },
  { "name": "Uzbekistan", "dial_code": "+998", "code": "UZ" },
  { "name": "Vanuatu", "dial_code": "+678", "code": "VU" },
  { "name": "Venezuela, Bolivarian Republic of Venezuela", "dial_code": "+58", "code": "VE" },
  { "name": "Vietnam", "dial_code": "+84", "code": "VN" },
  { "name": "Virgin Islands, British", "dial_code": "+1284", "code": "VG" },
  { "name": "Virgin Islands, U.S.", "dial_code": "+1340", "code": "VI" },
  { "name": "Wallis and Futuna", "dial_code": "+681", "code": "WF" },
  { "name": "Yemen", "dial_code": "+967", "code": "YE" },
  { "name": "Zambia", "dial_code": "+260", "code": "ZM" },
  { "name": "Zimbabwe", "dial_code": "+263", "code": "ZW" } 
];


export const getDialCode = (country) => {
  let code;
  dailCodes.map(data => {
    if(data.name === country){
      code = data.dial_code;
    }
  });
  return code;
}

export const getAllDialCode = () => {
  return dailCodes.length ? dailCodes.map(data => (
    <option value={`${data.dial_code}`}>{data.dial_code + ' ' + data.code}</option>
  )) : <option value="">Codes</option>
}


{/* <div class="input-group mb-3">
  <div class="input-group-prepend">
    <select class="input-group-text" id="basic-addon3">
      <option value="+234">+234 NG</option>
    </select>
  </div>
  <input 
    type="text" 
    class="form-control" 
    aria-describedby="basic-addon3"
    name="mobilePhone"
    onChange={this.handleChange}
    defaultValue={`${this.state.data.mobilePhone}`}
  >
</div> */}